#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $JETSETWILLY_HOME ]]; then
  echo "Error: JETSETWILLY_HOME not defined."
  exit 1
fi
if [[ ! -d $JETSETWILLY_HOME ]]; then
  echo "Error: directory not found: $JETSETWILLY_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

GAME=jsw
GAMEDIR=jet_set_willy
GAMENAME="Jet Set Willy"
SRCFILES=$(echo COPYING jet_set_willy{.skool,{,-bugs,-changelog,-facts,-pokes}.ref,{,-dark,-green,-plum}.css} jetsetwilly.py)
DHOME=$JETSETWILLY_HOME
GHREPO=jetsetwilly
GHHTMLOPTS="-T green -j style.css"

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
